import Head from 'next/head';
import { useState } from 'react'
import { connect } from "react-redux"
import { setInfo } from "../redux/actions/main"
import MainHeader from '../components/main-header';

const Home = (props): JSX.Element => {
  const { name, setInfo } = props;
  const [newName, setName] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <MainHeader />
      </div>

      <div>
        <p>Enter a Name {name}:</p>
        <input 
          type="text" 
          value={newName} 
          onChange={(e) => setName(e.target.value)}>

          </input>
          <button onClick={() => setInfo(newName)}>
            Submit
          </button>
      </div>
    </>
  )
};


const mapStateToProps = state => {
  return { name: state.main.name }
 }
 
 const mapDispatchToProps = {
   setInfo
 }
 
 export default connect(mapStateToProps, mapDispatchToProps)(Home)
