import Head from 'next/head';
import { useState } from 'react'
import { connect } from "react-redux"
import { setInfo } from "../redux/actions/main"
import MainHeader from '../components/main-header/main-header';
import Hero from '../components/hero/hero';

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <Hero />
      {/* <div>
        <p>Enter a Name {name}:</p>
        <input 
          type="text" 
          value={newName} 
          onChange={(e) => setName(e.target.value)}
        />
        <button onClick={() => setInfo(newName)}>
          Submit
        </button>
      </div> */}
    </>
  )
};

export default Home;

// const mapStateToProps = state => {
//   return {
//     name: state.main.name,
//     slides: state.slides
//   }
//  }
 
//  const mapDispatchToProps = {
//    setInfo
//  }
 
//  export default connect(mapStateToProps, mapDispatchToProps)(Home)